// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai-excuse": {
            "post": {
                "description": "Generate excuse candidates using AI. Requires premium plan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "Generate AI excuses",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateAiExcuseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateAiExcuseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden if not premium",
                        "schema": {
                            "$ref": "#/definitions/handlers.PremiumRequiredResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/excuse-templates": {
            "get": {
                "description": "Get excuse templates. Can filter by pack_id. Premium users can access all. Free users restricted from premium packs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "excuse-templates"
                ],
                "summary": "List excuse templates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pack ID to filter",
                        "name": "pack_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetExcuseTemplatesResponse"
                        }
                    }
                }
            }
        },
        "/excuse-templates/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "excuse-templates"
                ],
                "summary": "Get template details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseTemplateResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.TemplateNotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.TemplateInternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/excuses/{id}": {
            "delete": {
                "tags": [
                    "excuses"
                ],
                "summary": "Delete an excuse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Excuse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid Excuse ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseNotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseInternalErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "excuses"
                ],
                "summary": "Update an excuse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Excuse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateExcuseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseValidationErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseForbiddenResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseNotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseInternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/goals": {
            "get": {
                "description": "Get all goals for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "List goals",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetGoalsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalInternalErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalInternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new goal. Checks for plan limits.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "Create goal",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateGoalRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateGoalResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalValidationErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden if max goals reached",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalLimitReachedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalInternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/goals/{goal_id}/excuses": {
            "get": {
                "description": "List excuses, filters by retention days if strictly limited by entitlement.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "excuses"
                ],
                "summary": "List excuses for a goal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Goal ID",
                        "name": "goal_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From Date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "To Date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetExcusesResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Goal ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseInternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Upsert excuse for a date. Checks entitlement if using premium template.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "excuses"
                ],
                "summary": "Create or update an excuse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Goal ID",
                        "name": "goal_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Excuse Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateExcuseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseValidationErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseForbiddenResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseInternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/goals/{goal_id}/excuses/today": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "excuses"
                ],
                "summary": "Get today's excuse for a goal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Goal ID",
                        "name": "goal_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Goal ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseNotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExcuseInternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/goals/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "Delete goal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Goal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalNotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalInternalErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "goals"
                ],
                "summary": "Update goal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Goal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateGoalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateGoalResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalNotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.GoalInternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/me/plan": {
            "get": {
                "description": "Returns the user's current subscription plan and their active entitlements.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "Get current user plan and entitlements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetMePlanResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.PlanInternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Updates the user's subscription plan (e.g., from 'free' to 'premium').",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "Update user plan",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PostMePlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PostMePlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.PlanValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.PlanInternalErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateAiExcuseRequest": {
            "type": "object",
            "required": [
                "date",
                "goalId"
            ],
            "properties": {
                "context": {
                    "type": "string",
                    "example": "I had a lot of meetings"
                },
                "date": {
                    "type": "string",
                    "example": "2023-10-27"
                },
                "goalId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "tone": {
                    "type": "string",
                    "example": "serious"
                }
            }
        },
        "handlers.CreateAiExcuseResponse": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "I had unexpected urgent work.",
                        "I wasn't feeling well."
                    ]
                }
            }
        },
        "handlers.CreateExcuseRequest": {
            "type": "object",
            "required": [
                "date",
                "excuseText"
            ],
            "properties": {
                "date": {
                    "description": "YYYY-MM-DD",
                    "type": "string",
                    "example": "2023-10-27"
                },
                "excuseText": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "I overslept."
                },
                "templateId": {
                    "type": "string",
                    "example": "template_123"
                }
            }
        },
        "handlers.CreateGoalRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "notificationEnabled": {
                    "type": "boolean",
                    "example": true
                },
                "notificationTime": {
                    "type": "string",
                    "example": "20:00"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "example": "Read 10 pages"
                }
            }
        },
        "handlers.CreateGoalResponse": {
            "type": "object",
            "properties": {
                "goal": {
                    "$ref": "#/definitions/handlers.GoalResponse"
                }
            }
        },
        "handlers.ExcuseForbiddenResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Premium template entitlement required"
                }
            }
        },
        "handlers.ExcuseInternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Failed to create excuse"
                }
            }
        },
        "handlers.ExcuseNotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Excuse not found"
                }
            }
        },
        "handlers.ExcuseResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string",
                    "example": "2023-10-27"
                },
                "excuseText": {
                    "type": "string",
                    "example": "I overslept."
                },
                "goalId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "templateId": {
                    "type": "string",
                    "example": "template_123"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "handlers.ExcuseTemplateResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "excuseText": {
                    "type": "string",
                    "example": "My dog ate my homework."
                },
                "id": {
                    "type": "string",
                    "example": "template_123"
                },
                "isPremium": {
                    "type": "boolean",
                    "example": false
                },
                "packId": {
                    "type": "string",
                    "example": "pack_abc"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "funny",
                        "classic"
                    ]
                }
            }
        },
        "handlers.ExcuseValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Key: 'CreateExcuseRequest.Date' Error:Field validation for 'Date' failed on the 'required' tag"
                }
            }
        },
        "handlers.GetExcuseTemplatesResponse": {
            "type": "object",
            "properties": {
                "templates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ExcuseTemplateResponse"
                    }
                }
            }
        },
        "handlers.GetExcusesResponse": {
            "type": "object",
            "properties": {
                "excuses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ExcuseResponse"
                    }
                }
            }
        },
        "handlers.GetGoalsResponse": {
            "type": "object",
            "properties": {
                "goals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.GoalResponse"
                    }
                }
            }
        },
        "handlers.GetMePlanResponse": {
            "type": "object",
            "properties": {
                "entitlements": {
                    "description": "Entitlements struct might need examples in its own definition if not here",
                    "allOf": [
                        {
                            "$ref": "#/definitions/services.Entitlements"
                        }
                    ]
                },
                "plan": {
                    "type": "string",
                    "example": "premium"
                }
            }
        },
        "handlers.GoalInternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Failed to fetch goals"
                }
            }
        },
        "handlers.GoalLimitReachedResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Maximum goal limit reached for your plan"
                }
            }
        },
        "handlers.GoalNotFoundErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Goal not found"
                }
            }
        },
        "handlers.GoalResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "notificationEnabled": {
                    "type": "boolean",
                    "example": true
                },
                "notificationTime": {
                    "type": "string",
                    "example": "20:00"
                },
                "order": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Read 10 pages"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "handlers.GoalValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Key: 'CreateGoalRequest.Title' Error:Field validation for 'Title' failed on the 'required' tag"
                }
            }
        },
        "handlers.InternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Failed to generate excuses"
                }
            }
        },
        "handlers.PlanInternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Failed to get plan"
                }
            }
        },
        "handlers.PlanValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Key: 'PostMePlanRequest.Plan' Error:Field validation for 'Plan' failed on the 'required' tag"
                }
            }
        },
        "handlers.PostMePlanRequest": {
            "type": "object",
            "required": [
                "plan"
            ],
            "properties": {
                "plan": {
                    "type": "string",
                    "example": "premium"
                }
            }
        },
        "handlers.PostMePlanResponse": {
            "type": "object",
            "properties": {
                "entitlements": {
                    "$ref": "#/definitions/services.Entitlements"
                },
                "plan": {
                    "type": "string",
                    "example": "premium"
                }
            }
        },
        "handlers.PremiumRequiredResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "This feature requires a premium plan"
                }
            }
        },
        "handlers.TemplateInternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Failed to fetch templates"
                }
            }
        },
        "handlers.TemplateNotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Template not found"
                }
            }
        },
        "handlers.UpdateExcuseRequest": {
            "type": "object",
            "properties": {
                "excuseText": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "I overslept a lot."
                },
                "templateId": {
                    "type": "string",
                    "example": "template_123"
                }
            }
        },
        "handlers.UpdateGoalRequest": {
            "type": "object",
            "properties": {
                "notificationEnabled": {
                    "type": "boolean",
                    "example": false
                },
                "notificationTime": {
                    "type": "string",
                    "example": "21:00"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "example": "Read 20 pages"
                }
            }
        },
        "handlers.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Key: 'CreateAiExcuseRequest.GoalID' Error:Field validation for 'GoalID' failed on the 'required' tag"
                }
            }
        },
        "services.Entitlements": {
            "type": "object",
            "properties": {
                "canUseAiExcuse": {
                    "type": "boolean"
                },
                "canUsePremiumTemplates": {
                    "type": "boolean"
                },
                "logRetentionDays": {
                    "description": "nil = unlimited",
                    "type": "integer"
                },
                "maxGoals": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "What Went Wrong API",
	Description:      "API for what went wrong",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
